### ISSUE TITLE
Why extra android build task?

### ISSUE THREAD

**Issue by omares** [gshackles/xamarin-ci-sample#3]
Hey @gshackles ,

could you explain why your android build chain includes an extra "android-build" task where you use `MSBuild`? Afaik the `AndroidPackage` fake command create a build before packaging.

Maybe there is a special reason, to include the extra build task, i do not know about. :)

Thank you.

**Comment by gshackles** [comment]
The idea is to provide a build target for the app where I can make sure the app still compiles without needing to go through the extra packaging steps that aren't necessarily needed on every build. If you wanted to create a package on every build then you're right that the extra task would not be necessary.
